# Change these first
owner: ekalaya2015 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Malang
    url: https://malang.epuskesmas.id
  - name: Klaten
    url: https://klaten.epuskesmas.id
  - name: Badung
    url: https://badung.epuskesmas.id
  - name: Pasuruan
    url: https://pasuruan.epuskesmas.id
  - name: Lima Puluh Kota
    url: https://limapuluhkota.epuskesmas.id    
  - name: Gowa
    url: https://gowa.epuskesmas.id    
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime monitoring"
  introMessage: Uptime monitoring
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
